"""Initial schema

Revision ID: 032a32017cd2
Revises: 
Create Date: 2026-06-24 01:59:48.764381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032a32017cd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_invites',
    sa.Column('matchId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senderId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiverId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_invites_matchId'), 'match_invites', ['matchId'], unique=False)
    op.create_index(op.f('ix_match_invites_receiverId'), 'match_invites', ['receiverId'], unique=False)
    op.create_index(op.f('ix_match_invites_senderId'), 'match_invites', ['senderId'], unique=False)
    op.create_table('match_players',
    sa.Column('matchId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joinedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_players_matchId'), 'match_players', ['matchId'], unique=False)
    op.create_index(op.f('ix_match_players_userId'), 'match_players', ['userId'], unique=False)
    op.create_table('match_stats',
    sa.Column('matchId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('cleanSheet', sa.Boolean(), nullable=False),
    sa.Column('motm', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_stats_matchId'), 'match_stats', ['matchId'], unique=False)
    op.create_index(op.f('ix_match_stats_userId'), 'match_stats', ['userId'], unique=False)
    op.create_table('match_teams',
    sa.Column('matchId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_teams_matchId'), 'match_teams', ['matchId'], unique=False)
    op.create_table('match_verifications',
    sa.Column('matchId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('targetPlayerId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verifierId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['targetPlayerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verifierId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_verifications_matchId'), 'match_verifications', ['matchId'], unique=False)
    op.create_index(op.f('ix_match_verifications_targetPlayerId'), 'match_verifications', ['targetPlayerId'], unique=False)
    op.create_index(op.f('ix_match_verifications_verifierId'), 'match_verifications', ['verifierId'], unique=False)
    op.create_table('xp_logs',
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matchId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_logs_userId'), 'xp_logs', ['userId'], unique=False)
    op.drop_index(op.f('ix_players_auth_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_match_participants_matchId'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_userId'), table_name='match_participants')
    op.drop_table('match_participants')
    op.add_column('matches', sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('matches', sa.Column('matchDate', sa.DateTime(), nullable=False))
    op.add_column('matches', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('matches', sa.Column('hostId', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('matches', sa.Column('shortId', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.drop_index(op.f('ix_matches_creatorId'), table_name='matches')
    op.create_index(op.f('ix_matches_hostId'), 'matches', ['hostId'], unique=False)
    op.create_index(op.f('ix_matches_shortId'), 'matches', ['shortId'], unique=True)
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['hostId'], ['id'])
    op.drop_column('matches', 'dateTime')
    op.drop_column('matches', 'creatorId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('creatorId', sa.VARCHAR(), nullable=False))
    op.add_column('matches', sa.Column('dateTime', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['creatorId'], ['id'])
    op.drop_index(op.f('ix_matches_shortId'), table_name='matches')
    op.drop_index(op.f('ix_matches_hostId'), table_name='matches')
    op.create_index(op.f('ix_matches_creatorId'), 'matches', ['creatorId'], unique=False)
    op.drop_column('matches', 'shortId')
    op.drop_column('matches', 'hostId')
    op.drop_column('matches', 'password')
    op.drop_column('matches', 'matchDate')
    op.drop_column('matches', 'format')
    op.create_table('match_participants',
    sa.Column('matchId', sa.VARCHAR(), nullable=False),
    sa.Column('userId', sa.VARCHAR(), nullable=False),
    sa.Column('team', sa.VARCHAR(length=50), nullable=True),
    sa.Column('checkedIn', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_participants_userId'), 'match_participants', ['userId'], unique=False)
    op.create_index(op.f('ix_match_participants_matchId'), 'match_participants', ['matchId'], unique=False)
    op.create_table('players',
    sa.Column('auth_user_id', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=40), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), nullable=False),
    sa.Column('secondary_position', sa.VARCHAR(length=10), nullable=True),
    sa.Column('strong_foot', sa.VARCHAR(length=10), nullable=False),
    sa.Column('play_style', sa.VARCHAR(length=20), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=120), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('matches_played', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('goals', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('assists', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('tackles', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('saves', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('intercepts', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=1)
    op.create_index(op.f('ix_players_auth_user_id'), 'players', ['auth_user_id'], unique=1)
    op.drop_index(op.f('ix_xp_logs_userId'), table_name='xp_logs')
    op.drop_table('xp_logs')
    op.drop_index(op.f('ix_match_verifications_verifierId'), table_name='match_verifications')
    op.drop_index(op.f('ix_match_verifications_targetPlayerId'), table_name='match_verifications')
    op.drop_index(op.f('ix_match_verifications_matchId'), table_name='match_verifications')
    op.drop_table('match_verifications')
    op.drop_index(op.f('ix_match_teams_matchId'), table_name='match_teams')
    op.drop_table('match_teams')
    op.drop_index(op.f('ix_match_stats_userId'), table_name='match_stats')
    op.drop_index(op.f('ix_match_stats_matchId'), table_name='match_stats')
    op.drop_table('match_stats')
    op.drop_index(op.f('ix_match_players_userId'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_matchId'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index(op.f('ix_match_invites_senderId'), table_name='match_invites')
    op.drop_index(op.f('ix_match_invites_receiverId'), table_name='match_invites')
    op.drop_index(op.f('ix_match_invites_matchId'), table_name='match_invites')
    op.drop_table('match_invites')
    # ### end Alembic commands ###
