"""add team names to match

Revision ID: 6213c4e9b2fa
Revises: 0465c2fcab49
Create Date: 2026-06-26 16:36:42.806440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6213c4e9b2fa'
down_revision: Union[str, Sequence[str], None] = '0465c2fcab49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('teamAName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='Team A'))
    op.add_column('matches', sa.Column('teamBName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='Team B'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'teamBName')
    op.drop_column('matches', 'teamAName')
    # ### end Alembic commands ###
