"""Add MatchStats check flags and MutualVerifyFlag

Revision ID: 64ec366428f3
Revises: cff2f76856f1
Create Date: 2026-06-28 00:19:05.602131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64ec366428f3'
down_revision: Union[str, Sequence[str], None] = 'cff2f76856f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutual_verify_flags',
    sa.Column('playerAId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('playerBId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mutualVerifyCount', sa.Integer(), nullable=False),
    sa.Column('totalVerifyCount', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flaggedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playerAId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['playerBId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutual_verify_flags_playerAId'), 'mutual_verify_flags', ['playerAId'], unique=False)
    op.create_index(op.f('ix_mutual_verify_flags_playerBId'), 'mutual_verify_flags', ['playerBId'], unique=False)
    op.add_column('match_stats', sa.Column('createdAt', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('match_stats', sa.Column('isFlagged', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('match_stats', sa.Column('flagReason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_stats', 'flagReason')
    op.drop_column('match_stats', 'isFlagged')
    op.drop_column('match_stats', 'createdAt')
    op.drop_index(op.f('ix_mutual_verify_flags_playerBId'), table_name='mutual_verify_flags')
    op.drop_index(op.f('ix_mutual_verify_flags_playerAId'), table_name='mutual_verify_flags')
    op.drop_table('mutual_verify_flags')
    # ### end Alembic commands ###
