"""add xp and level columns to users

Revision ID: ca642388d6a2
Revises: bebb9d286800
Create Date: 2026-06-24 19:33:42.703183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca642388d6a2'
down_revision: Union[str, Sequence[str], None] = 'bebb9d286800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_stats', sa.Column('shotsOnTarget', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('keyPasses', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('interceptions', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('ballRecoveries', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('progressivePasses', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('blocks', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('clearances', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('bigSaves', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('penaltySaves', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('distributionAssists', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('duelsWon', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('aerialDuelsWon', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('yellowCards', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('redCards', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('ownGoals', sa.Integer(), nullable=False))
    op.add_column('match_stats', sa.Column('noShow', sa.Boolean(), nullable=False))
    op.add_column('match_stats', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('match_stats', sa.Column('verificationNote', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('match_verifications', sa.Column('disputeReason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('matches', sa.Column('teamAScore', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('teamBScore', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('needsUpgradeAnimation', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('pace', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('shooting', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('passing', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('dribbling', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('defending', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('physical', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('gk', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gk')
    op.drop_column('users', 'physical')
    op.drop_column('users', 'defending')
    op.drop_column('users', 'dribbling')
    op.drop_column('users', 'passing')
    op.drop_column('users', 'shooting')
    op.drop_column('users', 'pace')
    op.drop_column('users', 'needsUpgradeAnimation')
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    op.drop_column('matches', 'teamBScore')
    op.drop_column('matches', 'teamAScore')
    op.drop_column('match_verifications', 'disputeReason')
    op.drop_column('match_stats', 'verificationNote')
    op.drop_column('match_stats', 'status')
    op.drop_column('match_stats', 'noShow')
    op.drop_column('match_stats', 'ownGoals')
    op.drop_column('match_stats', 'redCards')
    op.drop_column('match_stats', 'yellowCards')
    op.drop_column('match_stats', 'aerialDuelsWon')
    op.drop_column('match_stats', 'duelsWon')
    op.drop_column('match_stats', 'distributionAssists')
    op.drop_column('match_stats', 'penaltySaves')
    op.drop_column('match_stats', 'bigSaves')
    op.drop_column('match_stats', 'clearances')
    op.drop_column('match_stats', 'blocks')
    op.drop_column('match_stats', 'progressivePasses')
    op.drop_column('match_stats', 'ballRecoveries')
    op.drop_column('match_stats', 'interceptions')
    op.drop_column('match_stats', 'keyPasses')
    op.drop_column('match_stats', 'shotsOnTarget')
    # ### end Alembic commands ###
