"""Add specific GK stats

Revision ID: cff2f76856f1
Revises: 6213c4e9b2fa
Create Date: 2026-06-28 00:11:10.358002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cff2f76856f1'
down_revision: Union[str, Sequence[str], None] = '6213c4e9b2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gkDiving', sa.Float(), nullable=False, server_default='60.0'))
    op.add_column('users', sa.Column('gkHandling', sa.Float(), nullable=False, server_default='60.0'))
    op.add_column('users', sa.Column('gkKicking', sa.Float(), nullable=False, server_default='60.0'))
    op.add_column('users', sa.Column('gkReflexes', sa.Float(), nullable=False, server_default='60.0'))
    op.add_column('users', sa.Column('gkPositioning', sa.Float(), nullable=False, server_default='60.0'))
    op.drop_column('users', 'gk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gk', sa.FLOAT(), nullable=False, server_default='60.0'))
    op.drop_column('users', 'gkPositioning')
    op.drop_column('users', 'gkReflexes')
    op.drop_column('users', 'gkKicking')
    op.drop_column('users', 'gkHandling')
    op.drop_column('users', 'gkDiving')
    # ### end Alembic commands ###
